apiVersion: skaffold/v1beta2
kind: Config
build:
  artifacts:
  - image: changeme
    context: .
    docker: {}
  tagPolicy:
    envTemplate:
      template: '{{.DOCKER_REGISTRY}}/pplboy-gmail-com/jenkinx-spring:{{.VERSION}}'
  local: {}
deploy:
  kubectl: {}
profiles:
- name: dev
  build:
    artifacts:
    - docker: {}
    tagPolicy:
      envTemplate:
        template: '{{.DOCKER_REGISTRY}}/pplboy-gmail-com/jenkinx-spring:{{.DIGEST_HEX}}'
    local: {}
  deploy:
    helm:
      releases:
      - name: jenkinx-spring
        chartPath: charts/jenkinx-spring
        setValueTemplates:
          image.repository: '{{.DOCKER_REGISTRY}}/pplboy-gmail-com/jenkinx-spring'
          image.tag: '{{.DIGEST_HEX}}'
